site_name: SpaCEX
repo_url: https://github.com/WLatSunLab/SpaCEX
repo_name: SpaCEX

nav:
  - index.md 
  - What you can do with SpaCEX:
    - Enhancement of the transcriptomic coverage in Fish-based ST: SpaCEX_ETC.md
    - SVG detection: SpaCEX_SVG.md
    - Spatial clustering: SpaCEX_SC.md
    

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: indido
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode